'use client';
import { useRef, useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowRight, Phone, Sparkles, Shield, Award, Star, Clock } from 'lucide-react';
import { getCachedGoogleReviews } from '../../services/googleReviewsService';
import GoogleReviewsCarousel from '../GoogleReviewsCarousel/GoogleReviewsCarousel';
import PartnersCompact from '../Partners/PartnersCompact';
const carImage = '/images/bd-6.webp'; const carImage400w = '/images/bd-6-400w.webp'; const carImage800w = '/images/bd-6-800w.webp'; const carImage1200w = '/images/bd-6-1200w.webp'; const carImage1600w = '/images/bd-6-1600w.webp';
import './ExteriorDetailingHero.scss';
export function ExteriorDetailingHero({ scrollTarget="#pricing", titleLine1="Exterior Detailing in", titleLine2="TORONTO &", titleLine3="SCARBOROUGH", titleLine4=null, subtitle="Tired of dull paint, water spots, and fading? <strong>Restore and protect your vehicle's exterior</strong> to stunning condition. From paint enhancement to comprehensive protection, we transform your vehicle's appearance." }) {
  const heroRef = useRef(null); const [reviews, setReviews] = useState({ rating:0, totalReviews:0, recentReviews:[] });
  useEffect(() => { const f = async () => { try { const d = await getCachedGoogleReviews(); if(d&&!d.error) setReviews({ rating:d.rating||0, totalReviews:d.totalReviews||0, recentReviews:(d.reviews||[]).slice(0,2) }); } catch(e) { console.error(e); } }; f(); }, []);
  return (<><div id="hero" className="exterior-detailing-hero" ref={heroRef}><div className="exterior-detailing-hero__background"><div className="exterior-detailing-hero__background-image"><img src={carImage} srcSet={`${carImage400w} 400w, ${carImage800w} 800w, ${carImage1200w} 1200w, ${carImage1600w} 1600w, ${carImage} 1920w`} sizes="100vw" alt={`${titleLine1} ${titleLine2} ${titleLine3||''}`} loading="eager" fetchPriority="high" decoding="async" width="1920" height="1080" /></div><div className="exterior-detailing-hero__background-overlay"></div><div className="exterior-detailing-hero__background-gradient"></div></div>
  <div className="exterior-detailing-hero__content"><div className="exterior-detailing-hero__container">
    <motion.div className="exterior-detailing-hero__trust-badges" initial={{ opacity:0, y:-20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.6 }}>{reviews.rating > 0 && (<div className="exterior-detailing-hero__trust-badge"><Star className="exterior-detailing-hero__trust-icon" fill="currentColor" /><div><span className="exterior-detailing-hero__trust-rating">{reviews.rating.toFixed(1)}</span><span className="exterior-detailing-hero__trust-text">{reviews.totalReviews > 0 ? `${reviews.totalReviews}+ Reviews` : 'Rated'}</span></div></div>)}<div className="exterior-detailing-hero__trust-badge"><Award className="exterior-detailing-hero__trust-icon" /><span>Expert Certified</span></div><div className="exterior-detailing-hero__trust-badge"><Shield className="exterior-detailing-hero__trust-icon" /><span>Lifetime Warranty</span></div><div className="exterior-detailing-hero__trust-badge"><Clock className="exterior-detailing-hero__trust-icon" /><span>Same-Day Service</span></div></motion.div>
    <motion.div initial={{ opacity:0, y:30 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8 }} className="exterior-detailing-hero__inner"><motion.div className="exterior-detailing-hero__title-section" initial={{ opacity:0, y:30 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:0.3 }}>
      <motion.h1 className="exterior-detailing-hero__main-title" initial={{ opacity:0, scale:0.9 }} animate={{ opacity:1, scale:1 }} transition={{ duration:0.8, delay:0.4 }}><motion.span className="exterior-detailing-hero__title-line exterior-detailing-hero__title-line--white" initial={{ opacity:0, x:-30 }} animate={{ opacity:1, x:0 }} transition={{ duration:0.6, delay:0.5 }}>{titleLine1}</motion.span><motion.span className="exterior-detailing-hero__title-line exterior-detailing-hero__title-line--highlight" initial={{ opacity:0, x:30 }} animate={{ opacity:1, x:0 }} transition={{ duration:0.6, delay:0.6 }}>{titleLine2}</motion.span>{titleLine3 && (<motion.span className="exterior-detailing-hero__title-line exterior-detailing-hero__title-line--highlight" initial={{ opacity:0, x:30 }} animate={{ opacity:1, x:0 }} transition={{ duration:0.6, delay:0.7 }}>{titleLine3}</motion.span>)}{titleLine4 && (<motion.span className="exterior-detailing-hero__title-line exterior-detailing-hero__title-line--white" initial={{ opacity:0, x:-30 }} animate={{ opacity:1, x:0 }} transition={{ duration:0.6, delay:0.8 }}>{titleLine4}</motion.span>)}</motion.h1>
      <motion.p className="exterior-detailing-hero__description" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:0.9 }} dangerouslySetInnerHTML={{ __html: subtitle }} />
      <motion.div className="exterior-detailing-hero__features" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:1.1 }}><motion.div className="exterior-detailing-hero__feature-item" whileHover={{ scale:1.1, y:-5 }} transition={{ type:"spring", stiffness:300 }}><Shield className="exterior-detailing-hero__feature-icon" /><span>Paint Protection</span></motion.div><motion.div className="exterior-detailing-hero__feature-item" whileHover={{ scale:1.1, y:-5 }} transition={{ type:"spring", stiffness:300 }}><Sparkles className="exterior-detailing-hero__feature-icon" /><span>Enhanced Shine</span></motion.div><motion.div className="exterior-detailing-hero__feature-item" whileHover={{ scale:1.1, y:-5 }} transition={{ type:"spring", stiffness:300 }}><Award className="exterior-detailing-hero__feature-icon" /><span>UV Defense</span></motion.div></motion.div>
      <motion.div className="exterior-detailing-hero__actions" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:1.3 }}><motion.a href="#contact" className="exterior-detailing-hero__action-button exterior-detailing-hero__action-button--primary" onClick={(e) => { e.preventDefault(); const el=document.querySelector('#contact'); if(el) el.scrollIntoView({ behavior:'smooth', block:'start' }); }} whileHover={{ scale:1.05, y:-2 }} whileTap={{ scale:0.95 }}><span>Get Free Quote</span><ArrowRight className="exterior-detailing-hero__icon" /></motion.a><motion.a href="tel:16476896109" className="exterior-detailing-hero__action-button exterior-detailing-hero__action-button--outline" whileHover={{ scale:1.05, y:-2 }} whileTap={{ scale:0.95 }}><Phone className="exterior-detailing-hero__icon" /><span>Call (647) 689-6109</span></motion.a></motion.div>
      <motion.div className="exterior-detailing-hero__service-shortcuts" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:1.5 }}><span className="exterior-detailing-hero__shortcuts-label">Related Services:</span><div className="exterior-detailing-hero__shortcuts-list"><Link href="/ceramic-coatings" className="exterior-detailing-hero__shortcut">Ceramic Coating</Link><Link href="/paint-correction" className="exterior-detailing-hero__shortcut">Paint Correction</Link><Link href="/auto-detail" className="exterior-detailing-hero__shortcut">Auto Detailing</Link></div></motion.div>
      {reviews.recentReviews.length > 0 && (<motion.div className="exterior-detailing-hero__reviews-section" initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:1.7 }}><div className="exterior-detailing-hero__reviews-header"><Star className="exterior-detailing-hero__reviews-icon" fill="currentColor" /><span>Recent Reviews</span></div><div className="exterior-detailing-hero__reviews-list">{reviews.recentReviews.map((r,i) => (<div key={i} className="exterior-detailing-hero__review-card"><div className="exterior-detailing-hero__review-header"><div className="exterior-detailing-hero__review-stars">{[...Array(5)].map((_,j) => (<Star key={j} className={`exterior-detailing-hero__review-star ${j<(r.rating||5)?'filled':''}`} size={12} fill={j<(r.rating||5)?'currentColor':'none'} />))}</div><span className="exterior-detailing-hero__review-name">{r.name}</span></div><p className="exterior-detailing-hero__review-text">"{r.message?.substring(0,80)}..."</p></div>))}</div></motion.div>)}
    </motion.div></motion.div>
  </div><div className="exterior-detailing-hero__partners"><PartnersCompact /></div><div className="exterior-detailing-hero__reviews"><GoogleReviewsCarousel /></div></div></div></>);
}
export default ExteriorDetailingHero;
